version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home 
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
  webproxy:
    build: .
    ports:
      - "80:80"
    container_name: proxy
    links:
      - "jenkins:jenkins_srv"
      - "gitlab:gitlab_srv"
    depends_on:
      - jenkins
      - gitlab

volumes:
  jenkins:
    external: false
  gitlab_config:
    external: false
  gitlab_logs:
    external: false
  gitlab_data:
    external: false

